### ISSUE TITLE
Gtk/Gdk/Cairo still  prerequisite?

### ISSUE THREAD

**Issue by blizzz** [Immington-Industries/way-cooler-bg#5]
I only looked a bit  through the code and commits, however it appears to me that with https://github.com/way-cooler/way-cooler-bg/commit/8ee8e7434afd9409c54f76178a4c7b03868ca9c9#diff-639fbc4ef05b315af92b4d836c31b023 gdk and cairo (thus also gtk?) were removed in favor of the image crate, which does not have these dependencies. Or am I mistaken?

**Comment by Timidger** [comment]
Ah, nice catch. Totally forgot to remove those from the `Cargo.toml` and `Cargo.lock`, and that's totally unnecessary dead code. I'll update the manifest and the readme. Thanks for bringing this to my attention!

**Comment by blizzz** [comment]
Cool, thx for confirming and the commit :) 🚀
